version: "3"

volumes:
  db-data: ~

services:
  db:
    build: ./db
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: null
    ports:
      - 65432:5432
